Eat-Local/eat-local-be

- app/models/user.rb
- db/migrate/20221203154914_create_users.rb
- db/schema.rb
- spec/factories/users.rb
- spec/models/user_spec.rb
made model tests for attributes for user
> 6 user database

- app/models/favorite.rb
- app/models/user.rb
- db/migrate/20221203163044_create_favorites.rb
- db/schema.rb
- pull_request_template.md
- spec/factories/favorites.rb
- spec/models/favorite_spec.rb
- spec/models/user_spec.rb
Test model attrbutes and relationships between users and favorites.
> 7 favorites database

- Gemfile
- Gemfile.lock
- app/controllers/graphql_controller.rb
- app/graphql/eat_local_be_schema.rb
- app/graphql/mutations/base_mutation.rb
- app/graphql/types/base_argument.rb
- app/graphql/types/base_connection.rb
- app/graphql/types/base_edge.rb
- app/graphql/types/base_enum.rb
- app/graphql/types/base_field.rb
- app/graphql/types/base_input_object.rb
- app/graphql/types/base_interface.rb
- app/graphql/types/base_object.rb
- app/graphql/types/base_scalar.rb
- app/graphql/types/base_union.rb
- app/graphql/types/favorite_type.rb
- app/graphql/types/mutation_type.rb
- app/graphql/types/node_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/user_type.rb
- config/routes.rb
- db/seeds.rb
> Graphql install

- Gemfile
- Gemfile.lock
- app/assets/config/manifest.js
- app/controllers/graphql_controller.rb
- app/graphql/types/favorite_type.rb
- app/graphql/types/query_type.rb
- app/graphql/types/user_type.rb
- config/routes.rb
- db/migrate/20221203154914_create_users.rb
- db/migrate/20221203163044_create_favorites.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/favorites.rb
- spec/factories/users.rb
- spec/models/favorite_spec.rb
- spec/models/user_spec.rb
> Graphql intro

- lib/tasks/fly.rake
> add seeds for prod db.

- app/assets/config/manifest.js
- app/graphql/types/user_type.rb
- db/seeds.rb
- fly.toml
- lib/tasks/fly.rake
> Update UserType to include fname, lname.

- app/controllers/graphql_controller.rb
- config/routes.rb
- db/seeds.rb
> update fname to lname in seeds file.

- Gemfile
- config/environments/development.rb
Moved the graphiql-rails gem out of development block in gemfile in order to fix deployment bugs
It has not been tested.  The graphql endpoints currently work locally, but have not been working in fly.io
> fix fly deployment bug

- Gemfile
> refactor: fix fly deployment bug in gemfile

- Gemfile
- Gemfile.lock
- app/services/yelp_service.rb
- spec/fixtures/vcr_cassettes/YelpService/_get_businesses/should_return_businesses_that_are_local_ordered_by_distance.yml
- spec/services/yelp_service_spec.rb
Kaelin created the service logic as well as signed up for the API_KEY, I then proceeded to test her implementation of the logic to ensure the logic is returning the correct data types and data in order for the application to run smoothly.
> Test and service logic

- app/facades/yelp_facade.rb
- spec/facades/yelp_facade_spec.rb
- spec/fixtures/vcr_cassettes/Business/_initialize/returns_an_array_of_Business_objects.yml
- spec/fixtures/vcr_cassettes/YelpFacade/_initialize/returns_an_array_of_Business_objects.yml
Kaelin created facade in order to abstract away complex details of how API calls, and object creation is made. Dominic wrote tests to ensure correct functionality.
> Test and logic business facade

- Gemfile
- Gemfile.lock
- app/graphql/types/query_type.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
- config/initializers/cors.rb
- db/seeds.rb
Needed CORS for BE & FE application communication, still need FE url. Find user by email in querytype graphql since FE will pass email instead of id. 
Tested with Postman
> cors setup

- app/graphql/types/query_type.rb
GraphQL not able to query user by email
Tested with Postman on localhost
> update user(email:) to find user by email.

- Gemfile
- app/models/user.rb
- db/migrate/20221203154914_create_users.rb
- db/schema.rb
- spec/graphql/mutations/create_user_spec.rb
- spec/models/user_spec.rb
created a test for the create_user mutation.  Created a query variable for the request body and tested the expected results.  
Created a sad path test for the validation of the user.email uniqueness
> Graphql testing

- .rubocop_todo.yml
- app/controllers/graphql_controller.rb
- app/graphql/mutations/create_favorite.rb
- app/graphql/types/favorite_type.rb
- app/graphql/types/mutation_type.rb
- db/migrate/20221203163044_create_favorites.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/favorites.rb
- spec/graphql/mutations/create_favorites_spec.rb
- spec/graphql/mutations/create_user_spec.rb
- spec/models/favorite_spec.rb
Co-authored-by: Erik Riggs riggs.erik@gmail.com, Co-authored-by: Benjamin Randolph neb417@gmail.com
created mutation for createFavorites and tested 
By creating test data and expectations of the results
> feat/test: createFavorite mutation endpoint and test

- app/controllers/api/v1/business_controller.rb
- lib/tasks/fly.rake
- spec/graphql/queries/user_spec.rb
Added sad path testing for user query 
tested the user query with an email that is not in the db
> Query test

- app/graphql/mutations/create_favorite.rb
- app/graphql/types/query_type.rb
- spec/graphql/queries/user_spec.rb
- spec/spec_helper.rb
removed user.all query 
it does need to be
> refactor: remove redundent code

- .rubocop_todo.yml
- app/graphql/mutations/create_favorite.rb
- app/graphql/mutations/destroy_favorite.rb
- spec/factories/favorites.rb
- spec/graphql/mutations/create_favorites_spec.rb
- spec/graphql/mutations/destroy_favorite_spec.rb
- spec/models/favorite_spec.rb
FE needed updated state of user upon creating/deleting favorites.
Update test suite to reflect changes and in Postman
> Return user create fav

- README.md
This PR was created in order to add the Miro board endpoints into the READme for documentation.
> add endpoints from Miro board to READme.

- app/graphql/mutations/create_favorite.rb
- app/graphql/types/favorite_type.rb
- db/migrate/20221203163044_create_favorites.rb
- db/schema.rb
- db/seeds.rb
- spec/factories/favorites.rb
- spec/graphql/mutations/create_favorites_spec.rb
- spec/graphql/mutations/destroy_favorite_spec.rb
- spec/graphql/queries/user_spec.rb
- spec/models/favorite_spec.rb
Add new migration for latitude and longitude.  Removed column for is_closed and added migration for price
Yes.  In the model and graphql object type using RSpec.  Also tested endpoints in postman
> Add coordinates favorites
